# -*- coding: utf-8 -*-
"""protein_name_ensemble.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C7LC3mGiQlxgF-K-UIEsgL72r0wZCCZj
"""
from Bio import SeqIO, Entrez
from Bio.Seq import Seq


import numpy as np
import itertools
import matplotlib.pyplot as plt

import gc
import pandas as pd


def get_request(url, headers={}):
    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()
    except requests.exceptions.RequestException as e:
        print("Error:", e)
        return None
    return response.json()
def get_protein_name(rsid):
    try:
        Entrez.email = "yourmail@something.com"
        handle = Entrez.esearch(db="gene", term=rsid)
        record = Entrez.read(handle)
        handle.close()
        gene_id = record["IdList"][0]
        handle = Entrez.efetch(db="gene", id=gene_id, retmode="xml")
        gene_record = Entrez.read(handle)
        handle.close()
        gene_symbol = gene_record[0]["Entrezgene_gene"]["Gene-ref"]["Gene-ref_locus"]
        print(gene_symbol)
        return gene_symbol
    except:
        print("Error: failed to retrieve information on SNP", rsid)
        return None

# Percorso del file GZIP
file_path = r'C:\Users\ricca\Desktop\ADNI.808_indiv.minGQ_21.pass.ADNI_ID.chr19_prep.txt.gz'

df = pd.read_csv(file_path, sep='\t', compression='gzip', dtype=str)

#modify the df to have in all the column a different SNPs and in all the rows a different patient
df = df.set_index('ID')
print(df)


gc.collect()


SNPs = df.index.tolist()
lookup_snpid_gene = pd.DataFrame(columns=['snpid', 'gene_name'])

for i in range(len(SNPs)):

  rsid = SNPs[i]
  print(i)

  gene = get_protein_name(rsid)
  if gene is not None:
    print("SNP {} is located in protein {}".format(rsid, gene))
    lookup_snpid_gene = pd.concat([lookup_snpid_gene, pd.DataFrame({'snpid': [rsid], 'gene_name': [gene]})], ignore_index=True)
df = df.loc[df.index.isin(lookup_snpid_gene['snpid'])]
print(df)
print(lookup_snpid_gene)

file_name = 'chr_19_protein_NBCI_transp_filtered.csv.gz'
file_path = r'C:\Users\ricca\Desktop\\' + file_name
df.to_csv(file_path, sep='\t', compression='gzip', index=True)
file_name = 'lookup_snpid_gene.csv.gz'
file_path = r'C:\Users\ricca\Desktop\\' + file_name
lookup_snpid_gene.to_csv(file_path, sep='\t', compression='gzip', index=True)
